<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [29]:
def matrix_mul(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        print ("Matrix multiplication not possible. Please check the dimensions.")
        return

    #Result Matrix
    result = [[0 for row in range(cols_B)] for col in range(rows_A)]
    print (result)
    
    for i in range(len(A)): 
  
      for j in range(len(B[0])): 
  
          for k in range(len(B)): 
                   result[i][j] += A[i][k] * B[k][j] 
            
    return result

A = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6]]

B = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]] 

result = matrix_mul(A, B)
   
for res in result:  
    print(res)    


[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [93]:
import random

def pick_a_number_from_list(A):
    sum=0
    cum_sum=[]
    for i in range(len(A)):
        sum = sum + A[i]
        cum_sum.append(sum)
    random_number = int(random.uniform(0,sum))
    number=0
    for index in range(len(cum_sum)):
        if(random_number>=cum_sum[index] and random_number<cum_sum[index+1]):
            return A[index+1]
    return number

def sampling_based_on_magnitued():
    A = [0,5,27,6,13,28,100,45,10,79]
    experiment_count = dict()
    
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        if number not in experiment_count:
            experiment_count[number] = 1
        else:
            experiment_count[number]+=1
    print(experiment_count)

sampling_based_on_magnitued()

{100: 38, 45: 11, 79: 25, 27: 6, 28: 8, 10: 4, 13: 4, 6: 2, 5: 1}


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [89]:
import re
def replace_digits(inputString):
   
    modified_string = '#' * len(re.sub('\D', '', inputString))
    return modified_string

input_str="a2b3c4"
modified_string=replace_digits(input_str)

if len(modified_string) > 0:
    print(input_str, ":",modified_string)
else:
    print("empty string")


a2b3c4 : ###


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [94]:
def display_dash_board(students, marks):
    
    top_5_students = []
    least_5_students = []
    students_within_25_and_75 = []
    
    dictionary = dict(zip(students,marks))
    for key, value in sorted(dictionary.items(), key=lambda item: item[1],reverse=True)[:5]:
        top_5_students.append("%s: %s" % (key, value))
        
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
          least_5_students.append("%s: %s" % (key, value)) 
    
    marks_len = len(marks)
    first_quartile = int(marks_len/4) 
    third_quartile = int(3*marks_len/4)
        
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[first_quartile:third_quartile]:
        (students_within_25_and_75).append("%s: %s" % (key, value))
    
    return top_5_students, least_5_students, students_within_25_and_75

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print('top_5_students')
for i in range(len(top_5_students)):
    print(top_5_students[i])

print('\n')    
print('least_5_students')
for i in range(len(least_5_students)):
    print(least_5_students[i])
    
print('\n')     
print('students_within_25_and_75')
for i in range(len(students_within_25_and_75)):
    print(students_within_25_and_75[i])

top_5_students
student8: 98
student10: 80
student2: 78
student5: 48
student7: 47


least_5_students
student3: 12
student4: 14
student9: 35
student6: 43
student1: 45


students_within_25_and_75
student9: 35
student6: 43
student1: 45
student7: 47
student5: 48


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [2]:
import math

def closest_points_to_p(S, P):
    
    S.sort(key=lambda x: math.sqrt((float(x[0]) - P[0]) ** 2 +
                                  (float(x[1]) - (P[1])) ** 2))
    closest_points_to_p=(S[:5])
    #print(data[:5])
    return closest_points_to_p

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)

print(points)

[(1, -1), (6, -7), (-1, -1), (6, 0), (1, 2)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [60]:
import math
import re

def i_am_the_one(red,blue,i):
    count = 0
    count1 = 0
    
    yes_or_no = "NO"
    coeff=re.findall(r'[\d\.\-\+]+', i)
    if len(coeff) > 1:
        for i in range(len(coeff)):
            coeff[i]=float(coeff[i])
            coeff[1]=float(coeff[1])
            denominator=math.sqrt((coeff[0]*coeff[0])+(coeff[1]*coeff[1]))
            denominator=round(denominator,1)
                       
        for i in range(len(red)):
                for k in range(0,2):
                    #print(float(red[i][0]))
                    numerator = (coeff[0]*float(red[i][0])+coeff[1]*float(red[i][1])+coeff[2])
                    distance=numerator/denominator
                    if(distance > 0):
                        count=count+1
                    else:
                        count=count-1
                       
        for i in range(len(blue)):
                for k in range(0,2):
                    numerator1 = (coeff[0]*float(blue[i][0])+coeff[1]*float(blue[i][1])+coeff[2])
                    distance1=numerator1/denominator
                    if(distance1 > 0):
                        count1=count1+1
                    else:
                        count1=count1-1
                        
    if(abs(count1) == count):
        yes_or_no = "YES"          
    else:
        yes_or_no = "NO"             
    
    return yes_or_no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [15]:
def curve_smoothing(S):
    output = S.split(',')

    index = 0
    next_value = 0
    last_index = 0
    last_value = 0

    while index < len(output):
        if output[index] != '_' or (index + 1 == len(output)):
            if output[index] != '_':
                next_value = int(output[index])
            else:
                next_value = 0
            new_value = (next_value + last_value) / (index - last_index + 1)
            for i in range(last_index, index + 1):
                output[i] = new_value
            last_value = new_value
            last_index = index
        index += 1

    output_str = [str(int(i)) for i in output]
    output = ", " . join(output_str)
    
    return output

S = ["_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in S:
    print (curve_smoothing(i))     


6, 6, 6, 6
20, 20, 20, 20, 20
16, 16, 16, 16, 16
10, 10, 12, 12, 12, 12, 4, 4, 4


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [69]:
from fractions import Fraction
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]

dict1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dict2 = {
'S1': 0,
'S2': 0,
'S3': 0
}

def compute_conditional_probabilites(A):
    for i in range(len(A)):
        k = A[i][0] + A[i][1]
        dict1[k] += 1
        dict2[A[i][1]] += 1

A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]
compute_conditional_probabilites(A)

print('Probability of P(F=F1|S==S1)', Fraction(dict1['F1S1']/dict2['S1']),',','P(F=F1|S==S2)', Fraction(dict1['F1S2']/dict2['S2']).limit_denominator(),',','P(F=F1|S==S3)', Fraction(dict1['F1S3']/dict2['S3']))
print('Probability of P(F=F2|S==S1)', Fraction(dict1['F2S1']/dict2['S1']),',','P(F=F2|S==S2)', Fraction(dict1['F2S2']/dict2['S2']).limit_denominator(),',','P(F=F2|S==S3)', Fraction(dict1['F2S3']/dict2['S3']).limit_denominator())
print('Probability of P(F=F3|S==S1)', Fraction(dict1['F3S1']/dict2['S1']),',  ','P(F=F3|S==S2)', Fraction(dict1['F3S2']/dict2['S2']).limit_denominator(),',','P(F=F3|S==S3)', Fraction(dict1['F3S3']/dict2['S3']).limit_denominator())
print('Probability of P(F=F4|S==S1)', Fraction(dict1['F4S1']/dict2['S1']),',','P(F=F4|S==S2)', Fraction(dict1['F4S2']/dict2['S2']),',  ','P(F=F4|S==S3)', Fraction(dict1['F4S3']/dict2['S3']).limit_denominator())
print('Probability of P(F=F5|S==S1)', Fraction(dict1['F5S1']/dict2['S1']),',','P(F=F5|S==S2)', Fraction(dict1['F5S2']/dict2['S2']),',  ','P(F=F5|S==S3)', Fraction(dict1['F5S3']/dict2['S3']))



Probability of P(F=F1|S==S1) 1/4 , P(F=F1|S==S2) 1/3 , P(F=F1|S==S3) 0
Probability of P(F=F2|S==S1) 1/4 , P(F=F2|S==S2) 1/3 , P(F=F2|S==S3) 1/3
Probability of P(F=F3|S==S1) 0 ,   P(F=F3|S==S2) 1/3 , P(F=F3|S==S3) 1/3
Probability of P(F=F4|S==S1) 1/4 , P(F=F4|S==S2) 0 ,   P(F=F4|S==S3) 1/3
Probability of P(F=F5|S==S1) 1/4 , P(F=F5|S==S2) 0 ,   P(F=F5|S==S3) 0


## <h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [15]:
def string_features(S1, S2):

    stmt1=S1.split()
    stmt2=S2.split()
    a = set(stmt1).intersection(set(stmt2))
    b = set(stmt1).difference(set(stmt2))
    c = set(stmt2).difference(set(stmt1))
    
    return len(a), list(b), list(c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

a, b, c = string_features(S1, S2)
print("a. Number of common words between S1, S2 : ", a)
print("b. Words in S1 but not in S2 : ", b)
print("c. Words in S2 but not in S1 : ", c)

a. Number of common words between S1, S2 :  7
b. Words in S1 but not in S2 :  ['5', 'F', 'first']
c. Words in S2 but not in S1 :  ['3', 'second', 'S']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [21]:
from math import log
  
def compute_log_loss(A):
    y=[]
    y_score=[]
    for list in A:
        y.append(list[0])
        y_score.append(list[1])
        
    print("Y : ", y)
    print("Y Score : ",y_score)
    
    return -(1.0/len(y))*sum([y[i]*log(y_score[i],10) + (1.0-y[i])*log(1.0-y_score[i],10) for i in range(len(y))])
                                               
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)

print(loss)

Y :  [1, 0, 0, 0, 0, 1, 1, 1]
Y Score :  [0.4, 0.5, 0.9, 0.3, 0.6, 0.1, 0.9, 0.8]
0.42430993457031635
